### ISSUE TITLE
[Question] Use trackball on both sides? 

### ISSUE THREAD

**Issue by 10bn** [dtwright/lily58-mods#1]
Hi, thank you for sharing this with us! 
I followed your guide and got everything working so far. 
I would really like to add a trackball also to the left side, but I don't know too much about programming jet. 
Would it be easy to add a trackball to the left side as well?

**Comment by dtwright** [comment]
Thanks! Sorry I didn't respond to this when you posted the issue, I missed the notification somehow. As far as using a trackball on both sides, I haven't messed with that yet - it should work in theory (the transport driver has code to send mouse data from the left to the right/master side) but I have not tried it. It should be easy enough for me to try it out and get it working; I should I have a chance to do so in the next couple weeks, I'll let you know what I find.

**Comment by 10bn** [comment]
That would be great thank you.
